server.port: 7002

logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring:
  datasource:
    url: jdbc:sqlite:product.sqlite/recommendation
    driver-class-name: org.sqlite.JDBC
---
spring.profiles: docker

server.port: 8080