server.port: 7002

logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring:
  datasource:
    url: jdbc:sqlite:product.sqlite
    driver-class-name: org.sqlite.JDBC
    username:
    password:

---
spring.profiles: docker

server.port: 8080