version: '2.1'

services:
  product:
    build: microservices/product-service
    mem_limit: 250m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - admin-server

  recommendation:
    build: microservices/recommendation-service
    mem_limit: 250m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - admin-server

  review:
    build: microservices/review-service
    mem_limit: 250m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - admin-server

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 250m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - review
      - recommendation
      - product
      - auth-server

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/gateway
    mem_limit: 250m
    ports:
      - "8443:8443"
    depends_on:
      - product-composite
      - auth-server

  auth-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/authorization-server
    mem_limit: 250m

  admin-server:
    build: spring-cloud/admin-server
    mem_limit: 250m
    ports:
      - "8769:8769"