server.port: 7001


logging:
  level:
    root: INFO
    se.magnus: DEBUG
spring:
  datasource:
    url: jdbc:sqlite:product.sqlite/product
    driver-class-name: org.sqlite.JDBC
---
spring.profiles: docker

server.port: 8080