server.port: 7001


logging:
  level:
    root: INFO
    se.magnus: DEBUG
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:sqlite::resource:product.sqlite
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  cloud:
    consul:
      host: 10.9.8.162
      port: 8500
      discovery:
        service-name: product-service
        health-check-path: /actuator/health
        health-check-critical-timeout: 20s
        prefer-ip-address: true
        health-check-interval: 10s
        #prefer-agent-address: true
        ip-address: 10.9.8.188
---
spring.profiles: docker

server.port: 8080

spring:
  application:
    name: product-service
  cloud:
    consul:
      host: 10.9.8.162
      port: 8500
      discovery:
        service-name: product-service
        register-health-check: false
        prefer-ip-address: false