server.port: 9999

spring.application.name: auth-server

spring:
  cloud:
    consul:
      host: 10.9.8.162
      port: 8500
      discovery:
        service-name: auth-server
        health-check-path: /actuator/health
        health-check-critical-timeout: 20s
        prefer-ip-address: true
        health-check-interval: 10s
        #prefer-agent-address: true
        ip-address: 10.9.8.188
  boot:
    admin:
      client:
        url: http://localhost:8769

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# security.oauth2.authorizationserver.jwt.enabled: false

---
spring.profiles: docker

spring:
  cloud:
    consul:
      host: 10.9.8.162
      port: 8500
      discovery:
        service-name: auth-server
        register-health-check: false
        prefer-ip-address: false
  boot:
    admin:
      client:
        url: http://admin-server:8769